export const EXPECTED_COMPACT_JAPANESE_NAMES = [
  "山田太郎",
  "山田花子",
  "佐藤健一",
  "鈴木一郎",
  "高橋健太",
  "高橋由美",
  "田中美咲",
] as const;

export const EXPECTED_SPACED_JAPANESE_NAMES = [
  "山田 太郎",
  "田中 美咲",
] as const;

export const EXPECTED_JAPANESE_SURNAMES = [
  "山田",
  "田中",
  "高橋",
  "佐藤",
  "鈴木",
] as const;

export const NON_PERSON_LOOKALIKES = [
  "山田製作所",
  "佐藤医院",
  "高橋橋梁株式会社",
  "鈴木模型店",
  "田中公園",
  "山田線",
  "高橋駅",
  "佐藤川",
  "鈴木峠",
  "田中交差点",
] as const;

export const PERSON_NAME_RICH_MARKDOWN = [
  "# 人名NER評価用テストデータ（Markdown版）",
  "",
  "司会：山田太郎",
  "記録：佐藤健一",
  "",
  "## 出席者",
  "",
  "| 部署 | 氏名 | 役割 |",
  "| --- | --- | --- |",
  "| 営業部 | 山田太郎 | 部長 |",
  "| 営業部 | 山田花子 | 主任 |",
  "| 品質保証部 | 佐藤健一 | QA |",
  "| 開発部 | 鈴木一郎 | 開発責任者 |",
  "| 開発部 | 高橋健太 | バックエンド |",
  "| 開発部 | 高橋由美 | フロントエンド |",
  "| 総務部 | 田中美咲 | 事務 |",
  "",
  "## 呼び方の違い",
  "",
  "山田 太郎",
  "田中 美咲",
  "山田",
  "田中",
  "高橋",
  "佐藤",
  "鈴木",
  "",
  "## 英語表記（単独行は後続評価）",
  "",
  "Taro Yamada",
  "Hanako Yamada",
  "",
  "## コードブロック",
  "",
  "```text",
  "Owner: 山田太郎",
  "Reviewer: 佐藤健一",
  "Developer: Kenta Takahashi",
  "```",
  "",
  "## JSON",
  "",
  "```json",
  "{",
  '  "manager": "山田太郎",',
  '  "reviewer": "佐藤健一",',
  '  "developer": "高橋健太",',
  '  "designer": "高橋由美"',
  "}",
  "```",
  "",
  "## CSV",
  "",
  "```csv",
  '"部署","氏名","備考"',
  '"開発,第一","高橋健太","API"',
  '"開発部","高橋由美","UI"',
  "```",
  "",
  "## 人名ではない例",
  "",
  ...NON_PERSON_LOOKALIKES,
].join("\n");
